__inline("./rocket.init.js")
__inline("./rocket.router.todosmvc.js")
__inline("../page/todos/js/model/rocket.collection.todolist.js")
__inline("../page/todos/js/model/rocket.model.todo.js")
__inline("../page/todos/js/view/rocket.pageview.todos.js")
__inline("../page/todos/js/view/rocket.subview.todo.js")
